# Generated by Django 3.2.25 on 2026-03-13 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sovage_vintage_cars_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=60)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('seller_contact', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bought_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars_bought', to='sovage_vintage_cars_app.user')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars_posted', to='sovage_vintage_cars_app.user')),
            ],
        ),
    ]
