# Generated by Django 3.2.25 on 2026-03-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovage_vintage_cars_app', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
